# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: Paradine
  version: 2.0.0
  termsOfService: https://localhost:8080/en/tos
  contact:
    name: API Support
    url: https://localhost:8080/en/support
    email: support@example.com
#  license:
#    name: Apache 2.0
#    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/api/paradine/v2
    description: Development server
  - url: https://localhost:8080/api/paradine/v2
    description: Development server with TLS Profile
paths:
  /restaurants:
    get:
      security: [] # No security
      parameters:
        - in: query
          name: page
          description: Page number, zero if not sent
          required: false
          schema:
            type: integer
            minimum: 0
        - in: query
          name: q
          description: Search term
          required: false
          schema:
            type: string
            minLength: 3
            maxLength: 42
        - in: query
          name: lat
          description: Latitude for geolocation search. Must be used in conbination with 'lng'
          required: false
          schema:
            type: number
            format: float
            minimum: -90.0
            maximum: 90.0
        - in: query
          name: lng
          description: Longitude for geolocation search. Must be used in conbination with 'lat'
          required: false
          schema:
            type: number
            format: float
            minimum: -180.0
            maximum: 180.0
      operationId: getRestaurants
      description: Returns a page of restaurants enriched with hourly safety indicators.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantsGetResponse'
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items. Non-negative number.
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages. Non-negative number.
          description: >-
            A page of restaurants.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >-
            Error response indicating incorrect / inconsistent query parameters.
  /restaurants/intended_visits:
    get:
      security:
        - jwt: []
      operationId: getMyIntendedVisits
      description: Returns the full list of intended visits for a logged-in user.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntendedVisitsGetResponse'
          description: >-
            A list of intended visits.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >-
            Error response indicating unauthorized access.
    post:
      security:
        - jwt: []
      operationId: createIntendedVisit
      description: Creates a new intended visit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIntendedVisitRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UuidResponse'
          description: >-
            UUID of the stored visit intention.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >-
            Error response indicating unauthorized access.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >
            Error response for cases when the backend rejects the attempt to add a new visit intention.

  /restaurants/intended_visits/{id}:
    delete:
      security:
        - jwt: []
      operationId: cancelIntendedVisit
      description: Cancels previously created intended visit
      parameters:
        - in: path
          name: id
          description: UUID of the stored visit intention
          required: true
          schema:
            type: string
            minLength: 36
            maxLength: 36
      responses:
        '200':
          description: >
            Visit intention was cancelled.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >
            Error response indicating unauthorized access.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >
            Error response when the visit intent wasn't found.

components:
  schemas:
    Envelope:
      type: object
      description: Properties of this object represent response metadata
      required:
        - version
      properties:
        version:
          description: API version
          type: string

    UuidResponse:
      description: Response for POST operation returning uuid of the created resource.
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              minLength: 36
              maxLength: 36
              description: UUID of the created resource assigned by server.
      example:
        version: 2.0
        id: 50e26c12-ff82-4131-adfc-9f377857bdf0

    RestaurantsGetResponse:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            restaurants:
              type: array
              items:
                $ref: '#/components/schemas/Restaurant'
      example:
        version: '2.0'
        restaurants:
          - id: aaaa-bbbb-cccc-dddd
            name: Shoti
            address:
              ru_RU: ул. Шевченко 20
              uk_UA: вул. Шевченка 20
              en_US: 20 Schevchenka str
            image: http://paradine.com/static/assets/5783853745/34587345934583.jpg
            geolat: 50.304567
            geolng: 30.344532
            safetyToday:
              - h: 0
                value: -1
              - h: 1
                value: -1
              - h: 2
                value: -1
              - h: 3
                value: -1
              - h: 4
                value: -1
              - h: 5
                value: -1
              - h: 6
                value: -1
              - h: 7
                value: -1
              - h: 8
                value: -1
              - h: 9
                value: 0
              - h: 10
                value: 0
              - h: 11
                value: 0
              - h: 12
                value: 10
              - h: 13
                value: 10
              - h: 14
                value: 10
              - h: 15
                value: 10
              - h: 16
                value: 10
              - h: 17
                value: 10
              - h: 18
                value: 20
              - h: 19
                value: 20
              - h: 20
                value: 20
              - h: 21
                value: 20
              - h: 22
                value: 10
              - h: 23
                value: -1
            safetyTomorrow:
              - h: 0
                value: -1
              - h: 1
                value: -1
              - h: 2
                value: -1
              - h: 3
                value: -1
              - h: 4
                value: -1
              - h: 5
                value: -1
              - h: 6
                value: -1
              - h: 7
                value: -1
              - h: 8
                value: -1
              - h: 9
                value: 0
              - h: 10
                value: 0
              - h: 11
                value: 0
              - h: 12
                value: 10
              - h: 13
                value: 10
              - h: 14
                value: 10
              - h: 15
                value: 10
              - h: 16
                value: 10
              - h: 17
                value: 10
              - h: 18
                value: 20
              - h: 19
                value: 20
              - h: 20
                value: 20
              - h: 21
                value: 20
              - h: 22
                value: 10
              - h: 23
                value: -1
    Restaurant:
      type: object
      required:
        - id
        - name
        - image
        - address
        - safetyToday
        - safetyTomorrow
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
        address:
          type: object
          additionalProperties:
            type: string
          example:
            ru_RU: 'ул. Шевченко 20'
            uk_UA: 'вул. Шевченка 20'
        geolat:
          type: number
          format: float
        geolng:
          type: number
          format: float
        safetyToday:
          type: array
          items:
            $ref: '#/components/schemas/HourlySafety'
        safetyTomorrow:
          type: array
          items:
            $ref: '#/components/schemas/HourlySafety'

    HourlySafety:
      type: object
      description: Representation of a restaurants' safety at a certain hour
      required:
        - h
        - value
      properties:
        h:
          description: hour, from 0 to 23
          type: integer
        value:
          description: safety indicator
          type: integer
      example:
        h: 17
        value: 10

    CreateIntendedVisitRequest:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            visit:
              $ref: '#/components/schemas/IntendedVisit'

    IntendedVisitsGetResponse:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            todayVisits:
              type: array
              items:
                $ref: '#/components/schemas/StoredIntendedVisit'
            tomorrowVisits:
              type: array
              items:
                $ref: '#/components/schemas/StoredIntendedVisit'
      example:
        version: '2.0'
        todayVisits:
          - id: 551f9da9-e0d9-468c-bb5d-a4a761c63dba
            when: 2020-07-28T17:00:00Z
            restaurantId: 5190ccd1-9b7b-4c5c-9025-495c7d9fa687
          - id: 2ac715d1-467b-472f-9bcb-e1c88c879cd4
            when: 2020-07-28T17:00:00Z
            restaurantId: 50e26c12-ff82-4131-adfc-9f377857bdf0
        tomorrowVisits:
          - id: 551f9da9-e0d9-468c-bb5d-a4a761c63dba
            when: 2020-07-29T17:00:00Z
            restaurantId: 5190ccd1-9b7b-4c5c-9025-495c7d9fa687
          - id: 2ac715d1-467b-472f-9bcb-e1c88c879cd4
            when: 2020-07-29T17:00:00Z
            restaurantId: 50e26c12-ff82-4131-adfc-9f377857bdf0

    StoredIntendedVisit:
      type: object
      properties:
        id:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: UUID of an intended visit.
        visitDate:
          description: Date and time of an intended visit in a format YYYY-mm-dd HH:00:00.
          type: string
          format: date-time
        restaurant:
          $ref: '#/components/schemas/Restaurant'
      required:
        - id
        - visitDate
        - restaurant
      description: Representation of a user's intention to go to a particular restaurant stored under a unique id.
      example:
        id: aaa1-bbb1-ccc1-ddd2
        visitDate: 2020-07-28 17:00:00
        restaurant:
          id: aaaa-bbbb-cccc-dddd
          name: Shoti
          address:
            ru_RU: ул. Шевченко 20
            uk_UA: вул. Шевченка 20
            en_US: 20 Schevchenka str
          image: http://paradine.com/static/assets/5783853745/34587345934583.jpg
          geolat: 50.304567
          geolng: 30.344532

    IntendedVisit:
      type: object
      description: Representation of a user's intention to go to a particular restaurant.
      required:
        - when
        - restaurantId
      properties:
        when:
          description: Date and time of an intended visit. Minutes are ignored.
          type: string
          format: date-time
        restaurantId:
          description: UUID of a particular existing restaurant.
          type: string
          format: uuid
          minLength: 36
          maxLength: 36

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'

  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
security:
  - jwt: []
  - basic: []
